version: "3.8"

volumes:
  pub:

services:
  package:
    image: dart:latest
    tty: true
    stdin_open: true
    working_dir: /home/package
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
      - PUB_CACHE=/vendor/pub-cache
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      - pub:/vendor/pub-cache
      - ./:/home/package

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
